# Generated by Django 4.2.1 on 2024-07-04 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types_nail_polish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Variant_nail_polish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('expiration_date', models.DateField()),
                ('types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nail_polish_and_currency.types_nail_polish')),
            ],
        ),
    ]
